sudo: false

language: java

cache:
  directories:
    - "$HOME/.cache"

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
  - mvn install -q -DskipTests -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -q

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -q -B -U -Prelease"
  skip_cleanup: true
  on:
    tags: false
